# Generated by Django 6.0.5 on 2026-05-14 13:36

import accounts.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrepreneurVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=40)),
                ('address', models.TextField(blank=True)),
                ('identity_type', models.CharField(choices=[('cnic', 'CNIC'), ('passport', 'Passport')], default='cnic', max_length=20)),
                ('identity_number', models.CharField(blank=True, max_length=80)),
                ('identity_front', models.FileField(blank=True, upload_to=accounts.models.verification_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'mp4', 'mov', 'webm'])])),
                ('identity_back', models.FileField(blank=True, upload_to=accounts.models.verification_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'mp4', 'mov', 'webm'])])),
                ('passport_photo', models.FileField(blank=True, upload_to=accounts.models.verification_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'mp4', 'mov', 'webm'])])),
                ('startup_website_url', models.URLField(blank=True)),
                ('proof_video_url', models.URLField(blank=True)),
                ('proof_video_file', models.FileField(blank=True, upload_to=accounts.models.verification_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'mp4', 'mov', 'webm'])])),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('admin_message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
