# Generated by Django 6.0.5 on 2026-05-14 14:12

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_entrepreneurverification_identity_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneurverification',
            name='identity_back',
            field=models.FileField(blank=True, upload_to=accounts.models.verification_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf']), accounts.models.validate_identity_file_size, accounts.models.validate_identity_file_content]),
        ),
        migrations.AlterField(
            model_name='entrepreneurverification',
            name='identity_front',
            field=models.FileField(blank=True, upload_to=accounts.models.verification_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf']), accounts.models.validate_identity_file_size, accounts.models.validate_identity_file_content]),
        ),
        migrations.AlterField(
            model_name='entrepreneurverification',
            name='passport_photo',
            field=models.FileField(blank=True, upload_to=accounts.models.verification_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf']), accounts.models.validate_identity_file_size, accounts.models.validate_identity_file_content]),
        ),
        migrations.AlterField(
            model_name='entrepreneurverification',
            name='proof_video_file',
            field=models.FileField(blank=True, upload_to=accounts.models.verification_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'webm']), accounts.models.validate_video_file_size, accounts.models.validate_video_file_content]),
        ),
    ]
