# Generated by Django 6.0.5 on 2026-05-14 13:36

import django.core.validators
import django.db.models.deletion
import marketplace.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='admin_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='document_file',
            field=models.FileField(blank=True, upload_to=marketplace.models.proposal_document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='proposal',
            name='proof_video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='startup_website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='InvestmentAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('virtual-escrow', 'Virtual Escrow'), ('stripe', 'Stripe'), ('jazzcash', 'JazzCash'), ('easypaisa', 'Easypaisa')], default='virtual-escrow', max_length=20)),
                ('equity_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('profit_share_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('expected_return_note', models.TextField(blank=True)),
                ('term_months', models.PositiveIntegerField(blank=True, null=True)),
                ('terms_snapshot', models.TextField()),
                ('accepted', models.BooleanField(default=True)),
                ('accepted_name', models.CharField(max_length=160)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('cancelled', 'Cancelled')], default='accepted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entrepreneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_investment_agreements', to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_agreements', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='marketplace.proposal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
