# Generated by Django 6.0.5 on 2026-05-14 14:12

import django.core.validators
import django.db.models.deletion
import marketplace.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_proposal_admin_message_proposal_document_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentagreement',
            name='entrepreneur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_investment_agreements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investmentagreement',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investment_agreements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investmentagreement',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='marketplace.proposal'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='document_file',
            field=models.FileField(blank=True, upload_to=marketplace.models.proposal_document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'jpg', 'jpeg', 'png']), marketplace.models.validate_proposal_document_size, marketplace.models.validate_proposal_document_content]),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='marketplace.proposal'),
        ),
    ]
